{
	"version": 1507752216,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/jeans-sheet0.png",
		"images/tshirt-sheet0.png",
		"images/shorts-sheet0.png",
		"images/topic-sheet0.png",
		"images/ball-sheet0.png",
		"images/termometr-sheet0.png",
		"images/helpera-sheet0.png",
		"images/helperb-sheet0.png",
		"images/helperstuff-sheet0.png",
		"images/helperc-sheet0.png",
		"images/helperd-sheet0.png",
		"images/helpere-sheet0.png",
		"images/helperf-sheet0.png",
		"images/clothes_boss_cap_1_a-sheet0.png",
		"images/clothes_boss_coat_2_c-sheet0.png",
		"images/clothes_boss_gloves_3_d-sheet0.png",
		"images/clothes_boss_scarf_1_b-sheet0.png",
		"images/clothes_boss_socks_6_f-sheet0.png",
		"images/clothes_boss_suit_4_c-sheet0.png",
		"images/clothes_boss_suitpants_5_e-sheet0.png",
		"images/clothes_boss_boots_1_f-sheet0.png",
		"images/clothes_boss_badloon_6_c-sheet0.png",
		"images/girl-sheet0.png",
		"images/background-sheet0.png",
		"images/termometr_rtut-sheet0.png",
		"images/boy-sheet0.png",
		"media/main song.m4a",
		"media/main song.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}